### PR TITLE
Add FRAMEBUFFER configuration option

### PR DESCRIPTION
**Pull request by lekkas**
See https://forums.resin.io/t/raspberrypi-3-with-pitft-3-5-restive-touch-electronjs/2228/22

### CODE REVIEW

**Comment by lurch** [comment]
I'm a bit confused, how does the `master` branch on this repo relate to the https://github.com/resin-io/resin-electronjs/tree/framebuffer branch? (which _does_ already set this `FRAMEBUFFER` option)
See also #39 
Ping @imrehg

**Comment by imrehg** [comment]
@lekkas @lurch I think the thing is: `master`: HDMI, `framebuffer`: framebuffer such as PiTFT support. Don't think we can mix the two, but @curcuz should be the arbitrator of that. Maybe it's more of a discovery problem, that there's another branch? Or could it be combined in a sane way?

**Comment by lurch** [comment]
Is this fixed by #66 ?

**Comment by curcuz** [comment]
@lurch yes, thanks for the reference :)

**Pull request closed without merging**
