### PR TITLE
increase available shm memory size

### LINKED ISSUE #44: Large image handling crash
If I use any large images or do anything a little challenging within the renderer process chromium crashes not giving any error codes etc. The screen basically just goes blank.

I am using an Intel NUC7I5BNK with a pcap screen

Here is a fork of this repo that just has a large image set as a background, if you try to zoom in to it you will get the same issue that I have here. - https://github.com/OllieLy/resin-electronjs

Every now and again I get this on the resin logs:

```
[182:0625/154212.641834:FATAL:bus.cc(1197)] D-Bus connection was disconnected. Aborting.
#0 0x000001cd013e <unknown>
#1 0x000001cb53db <unknown>
#2 0x000002fe74b0 <unknown>
#3 0x7f3a25eea1d1 dbus_connection_dispatch
#4 0x000002fe8109 <unknown>
#5 0x000001cb883e <unknown>
#6 0x000001d0b05c <unknown>
#7 0x000001d0b308 <unknown>
#8 0x000001d0b66b <unknown>
#9 0x000001cbab99 <unknown>
#10 0x000001d0adf7 <unknown>
#11 0x000001ced600 <unknown>
#12 0x000001d22fb5 <unknown>
#13 0x000001cfd753 <unknown>
#14 0x7f3a2809c064 start_thread
#15 0x7f3a214ce62d clone

xinit: connection to X server lost

waiting for X server to shut down (EE) Server terminated successfully (0). Closing log file
```

Front logo [Front conversations](https://app.frontapp.com/open/top_1y6b)

### PR DESCRIPTION
**Pull request by petrosagg**
fixes #44

### CODE REVIEW

**Review by curcuz — APPROVED** [review]

**Comment by danielmahon** [comment]
@petrosagg Awesome! I hope this fixes a performance issue I've been seeing with loading multiple images on a screen. Can you explain what this fix is doing?

**Comment by petrosagg** [comment]
@danielmahon chromium is a multi-process system and it uses shared memory to communicate between them. Shared memory on linux is implemented as files under `/dev/shm` and by default this mounted as a tmpfs with a max size of 64MB. This fix is unmounting the 64MB capped tmpfs and remounts an uncapped one so the limit becomes the system memory. We are thinking of adding this change deeper in resinOS so that containers don't need to mess with it

I didn't notice any change in performance after this fix in my tests

**Comment by danielmahon** [comment]
Thanks, @petrosagg, I guess I should have specified, by "performance" I meant that Electron would crash when displaying/interacting with multiple images on the screen, which I attributed to Chromium/Electron limitations. I'll let you know if this helps the issue.

**Comment by petrosagg** [comment]
Oh. Yeah it definitely solves this problem

**Comment by danielmahon** [comment]
@petrosagg So far so good! Wish I would have looked into this before... I definitely acquired some gray hairs because of it. 😉

**Pull request merged**
